version: '2'

services:

  bigfiveforlife:
    container_name: bigfiveforlife1
    #build: . # build from Dockerfile
    image: tbk/bigfiveforlife
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "9001:9001"
    volumes:
      - /var/log:/var/log