spring.application.name: 'bigfive'
spring.profiles.active: development

spring.jpa.database-platform: 'org.tbk.bigfive.sqlite.SQLiteDialect'
spring.jpa.hibernate.ddl-auto: 'create-drop'

app.name: bigfive (dev)
app.description: an app for named lists

server.port: 8080
server.use-forward-headers: true
server.compression.enabled: true

management.port: 9001
management.context-path: /actuator

#spring.boot.admin.url: http://localhost:9080

# LOGGING
logging.path: ./var/log
logging.file: application.log
logging.config: classpath:logback-development.xml
logging.level.org.springframework: INFO

spring.jpa.show-sql: true
